site_name: 天启PythonAPI
site_url: https://rdhuht.github.io/tianqiPythonAPI
site_description: 展示天启IDE的图形化编程基础内容
site_author: rdhuht cui
repo_url: https://github.com/rdhuht/tianqiPythonAPI
repo_name: tianqiPythonAPI
edit_uri: ""

theme:
  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换成夜间模式

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换成白天模式

  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    # - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - codehilite:
      guess_lang: true
      linenums: false
  # - toc:
  #     permalink: true
  - footnotes
  - meta
  - def_list

  # - pymdownx.highlight:
  #   anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  # - pymdownx.betterem:
  #     smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/ShangHai

extra:
  # social:
  #   - icon: fontawesome/solid/paper-plane
  #     link: mailto:<email-address>
  generator: false

nav:
  - 首页: 
    - index.md

  - 常用:
    - 时间: Python/time.md
    - 数学: Python/math.md
    - 串口: Python/tqm/serial.md

  - 主板: 
    - 加速度: Python/tqm/accelerometer.md
    - 无线网络接入点: Python/tqm/AP.md
    - 点阵屏: Python/tqm/display.md
    - 物联网: Python/tqm/mqtt.md
    - 计时器: Python/tqm/timer.md
    - 无线局域网: Python/tqm/wlan.md

  - 集成功能板:
    - 蜂鸣器: Python/tq_s1/buzzer.md
    - 温湿度传感器: Python/tq_s1/DHT.md
    - 按键: Python/tq_s1/key.md
    - 光线传感器: Python/tq_s1/light.md
    - 彩灯: Python/tq_s1/RGB.md
    - 触摸传感器: Python/tq_s1/touch.md
    - 声音传感器: Python/tq_s1/voice.md

  - 转接板:
      - 按钮: Python/tq_e1/button.md
      - 蜂鸣器: Python/tq_e1/buzzer.md
      - 颜色传感器: Python/tq_e1/colorSensor.md
      - 四位数码管: Python/tq_e1/digitalTube.md
      - 风扇: Python/tq_e1/fan.md
      - 火焰传感器: Python/tq_e1/flameSensor.md
      - 人体红外传感器: Python/tq_e1/humanInfrared.md
      - 光线传感器: Python/tq_e1/light.md
      - 灯串: Python/tq_e1/lightStrip.md
      - 磁敏传感器: Python/tq_e1/magnetometer.md
      - TT马达: Python/tq_e1/motor.md
      - 全彩灯: Python/tq_e1/RGB.md
      - 旋钮传感器: Python/tq_e1/rotarySwitch.md
      - 舵机: Python/tq_e1/servo.md
      - 土壤传感器: Python/tq_e1/soilHumidity.md
      - 触摸传感器: Python/tq_e1/touch.md
      - 超声波传感器: Python/tq_e1/ultrasonic.md
      - 声音传感器: Python/tq_e1/voice.md
      - 水泵: Python/tq_e1/waterPump.md

  - 小车:
      - 避障传感器: Python/tq_car/avoid.md
      - 蜂鸣器: Python/tq_car/buzzer.md
      - 动作: Python/tq_car/car.md
      - 颜色传感器: Python/tq_car/color.md
      - 灯光: Python/tq_car/lamplight.md
      - 马达: Python/tq_car/motor.md
      - 巡线: Python/tq_car/trace.md
      - 声音传感器: Python/tq_car/voice.md
