site_name: 天启PythonAPI
site_url: https://rdhuht.github.io/tianqiPythonAPI
site_description: 展示天启IDE的图形化编程基础内容
site_author: rdhuht cui
repo_url: https://github.com/rdhuht/tianqiPythonAPI
repo_name: tianqiPythonAPI
edit_uri: ""

theme:
  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换成夜间模式

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换成白天模式

  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    # - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - codehilite:
      guess_lang: true
      linenums: false
  # - toc:
  #     permalink: true
  - footnotes
  - meta
  - def_list

  # - pymdownx.highlight:
  #   anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  # - pymdownx.betterem:
  #     smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/ShangHai

extra:
  # social:
  #   - icon: fontawesome/solid/paper-plane
  #     link: mailto:<email-address>
  generator: false

nav:
  - 首页:
    - index.md
  - Python: 
    - 天启主板tqm: 
      - 点阵屏display: Python/tqm/00_display.md
      - 三轴传感器accelerometer: Python/tqm/01_accelerometer.md
      - 串口serial: Python/tqm/03_serial.md
      # - 时间time:
      # - 无线局域网wlan:
      # - 无线局域网热点AP:
      # - 物联网MQTT:
      # - 数学math:
    # - 天启集成功能板tqs1:
    #   - 触摸传感器touch:
    #   - 按键key:
    #   - 光线传感器light:
    #   - 声音传感器voice:
    #   - 蜂鸣器music:
    #   - 彩灯RGB:
    #   - 温湿度传感器DHT:
