name: publish site

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      - run: python -m pip install mkdocs-material
      - run: python -m pip install mkdocs-git-revision-date-localized-plugin
      - run: python -m pip install mkdocs-glightbox
      - run: python -m pip install mkdocs build
      - run: mkdocs gh-deploy --force
